import AuraLegacyToolPage from '@/components/dev-tools/AuraLegacyToolPage';

const page = {
  "documentClassName": "legacy-tool-document",
  "bodyClassName": "legacy-tool-route",
  "title": "Habit Tracker",
  "headMarkup": "<style>\n        :root { --bg:#0a0d12; --panel:#121820; --border:#283341; --text:#f8fafc; --muted:#94a3b8; --accent:#22c55e; }\n        *{box-sizing:border-box} body{margin:0;font-family:\"Segoe UI\",sans-serif;background:radial-gradient(circle at top,#17293c 0%,var(--bg) 42%);color:var(--text)}\n        .app{padding:24px;display:grid;gap:18px}.layout{display:grid;grid-template-columns:360px 1fr;gap:18px}\n        .panel{background:rgba(18,24,32,.94);border:1px solid var(--border);border-radius:18px;padding:18px}\n        h1,h2,h3,p{margin:0}.small{font-size:13px;color:var(--muted)}\n        .stack{display:grid;gap:12px}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}\n        input,select,button{font:inherit;color:inherit;background:#0f141b;border:1px solid var(--border);border-radius:12px;padding:10px 12px}\n        button{cursor:pointer}.primary{background:rgba(34,197,94,.14);border-color:rgba(34,197,94,.42)}\n        .icon-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.icon-btn{padding:10px;border-radius:12px}\n        .icon-btn.active{border-color:rgba(34,197,94,.45);background:rgba(34,197,94,.08)}\n        .habit-list{display:grid;gap:12px}.habit-card{display:grid;grid-template-columns:auto 1fr auto;gap:12px;align-items:center;padding:12px;border:1px solid var(--border);border-radius:14px;background:#0f141b}\n        .habit-card.dragging{opacity:.5}.habit-icon{width:42px;height:42px;border-radius:12px;display:grid;place-items:center}\n        .hit-btn{width:46px;height:46px;border-radius:14px;font-size:20px}\n        .hit-btn.done{background:rgba(34,197,94,.18);border-color:rgba(34,197,94,.5)}\n        .detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}\n        .heatmap, .weekly{display:grid;gap:12px}.legend{display:flex;gap:8px;align-items:center}\n        .legend span{display:inline-block;width:12px;height:12px;border-radius:3px}\n        .weekly-chart{display:flex;gap:12px;align-items:flex-end;height:180px}\n        .bar-group{flex:1;display:grid;gap:6px;justify-items:center}.bar{width:24px;border-radius:8px 8px 0 0;background:var(--accent)}\n        .modal{position:fixed;inset:0;background:rgba(0,0,0,.66);display:none;place-items:center;padding:20px}.modal.show{display:grid}\n        .modal-card{width:min(900px,100%);max-height:90vh;overflow:auto}\n        @media(max-width:960px){.layout,.detail-grid{grid-template-columns:1fr}}\n    </style>",
  "bodyMarkup": "<div class=\"app\">\n        <div><h1>Habit Tracker</h1><p class=\"small\" style=\"margin-top:8px;\">Daily tracking, streaks, weekly targets, drag-and-drop ordering, and per-habit history.</p></div>\n        <div class=\"layout\">\n            <section class=\"panel stack\">\n                <h2>Add Habit</h2>\n                <input id=\"habitName\" placeholder=\"Habit name\">\n                <div class=\"icon-grid\" id=\"iconGrid\"></div>\n                <div class=\"row\">\n                    <select id=\"targetType\"><option value=\"daily\">Daily</option><option value=\"weekly\">X times per week</option></select>\n                    <input id=\"targetCount\" type=\"number\" min=\"1\" max=\"7\" value=\"4\">\n                    <input id=\"habitColor\" type=\"color\" value=\"#22c55e\" style=\"width:64px; padding:4px;\">\n                </div>\n                <button id=\"addHabitBtn\" class=\"primary\">Add habit</button>\n            </section>\n\n            <section class=\"panel stack\">\n                <div class=\"row\" style=\"justify-content:space-between;\">\n                    <h2>Today</h2>\n                    <div class=\"small\" id=\"todayLabel\"></div>\n                </div>\n                <div id=\"habitList\" class=\"habit-list\"></div>\n                <div id=\"emptyState\" class=\"small\">No habits yet.</div>\n            </section>\n        </div>\n\n        <section class=\"panel detail-grid\">\n            <div class=\"heatmap\">\n                <h2>Monthly Heatmap</h2>\n                <div id=\"heatmapHost\"></div>\n            </div>\n            <div class=\"weekly\">\n                <h2>Weekly Completion Chart</h2>\n                <div id=\"weeklyChart\" class=\"weekly-chart\"></div>\n            </div>\n        </section>\n    </div>\n\n    <div id=\"detailModal\" class=\"modal\">\n        <div class=\"panel modal-card\">\n            <div class=\"row\" style=\"justify-content:space-between;\">\n                <h2 id=\"detailTitle\">Habit Detail</h2>\n                <button id=\"closeDetailBtn\">Close</button>\n            </div>\n            <div class=\"detail-grid\" style=\"margin-top:16px;\">\n                <div class=\"stack\">\n                    <div class=\"small\" id=\"detailMeta\"></div>\n                    <div id=\"detailHistory\" class=\"stack\"></div>\n                </div>\n                <div id=\"detailHeatmap\"></div>\n            </div>\n        </div>\n    </div>",
  "scripts": [],
  "externalScripts": ["/converted-inline/habit-tracker.js"]
};

export const title = page.title;

export default function HabitTracker() {
  return <AuraLegacyToolPage {...page} />;
}
