import LegacyHtmlPage from '@/components/legacy/LegacyHtmlPage';

const page = {
  "documentClassName": "legacy-tool-document",
  "bodyClassName": "legacy-tool-route",
  "title": "PRISM Config Status",
  "headMarkup": "<style>\n        body {\n            margin: 0;\n            min-height: 100vh;\n            font-family: \"Segoe UI\", Arial, sans-serif;\n            background: linear-gradient(180deg, #07111f 0%, #0f172a 100%);\n            color: #e2e8f0;\n            display: grid;\n            place-items: center;\n        }\n\n        .panel {\n            width: min(680px, calc(100vw - 32px));\n            background: rgba(15, 23, 42, 0.92);\n            border: 1px solid rgba(148, 163, 184, 0.22);\n            border-radius: 18px;\n            padding: 24px;\n            box-shadow: 0 24px 80px rgba(0, 0, 0, 0.35);\n        }\n\n        h1 {\n            margin: 0 0 8px;\n            font-size: 28px;\n        }\n\n        p {\n            margin: 0 0 16px;\n            color: #cbd5e1;\n            line-height: 1.5;\n        }\n\n        .status-card {\n            background: rgba(52, 211, 153, 0.08);\n            border: 1px solid rgba(52, 211, 153, 0.25);\n            border-radius: 12px;\n            padding: 16px;\n            margin-bottom: 16px;\n        }\n\n        .status-card h3 {\n            margin: 0 0 8px;\n            font-size: 16px;\n            color: #34d399;\n        }\n\n        .status-card p {\n            margin: 0;\n            font-size: 14px;\n            color: #a7f3d0;\n        }\n\n        .endpoint-box {\n            background: #020617;\n            border: 1px solid rgba(148, 163, 184, 0.24);\n            border-radius: 10px;\n            padding: 14px;\n            font: 13px/1.5 Consolas, \"Courier New\", monospace;\n            color: #93c5fd;\n            word-break: break-all;\n            margin-top: 8px;\n        }\n\n        code {\n            background: rgba(148, 163, 184, 0.12);\n            padding: 2px 6px;\n            border-radius: 6px;\n        }\n\n        .info-note {\n            background: rgba(96, 165, 250, 0.08);\n            border: 1px solid rgba(96, 165, 250, 0.2);\n            border-radius: 10px;\n            padding: 14px;\n            font-size: 13px;\n            color: #93c5fd;\n            line-height: 1.6;\n        }\n    </style>",
  "bodyMarkup": "<main class=\"panel\">\n        <h1>🔐 PRISM API Proxy</h1>\n        <p>Your AI tools now use a secure Azure Function proxy. <strong>No API keys are stored client-side or in your\n                code.</strong></p>\n\n        <div class=\"status-card\">\n            <h3>✅ Groq API — Active</h3>\n            <p>All AI tools route through the Azure proxy. The API key is stored securely in Azure Application Settings.\n            </p>\n            <div class=\"endpoint-box\">\n                POST\n                https://prism-ai-browser-api-hcb9hra7e8eecjca.centralindia-01.azurewebsites.net/api/prism_groq_devspace\n            </div>\n        </div>\n\n        <div class=\"status-card\" style=\"border-color: rgba(148, 163, 184, 0.2); background: rgba(148, 163, 184, 0.05);\">\n            <h3 style=\"color: #94a3b8;\">⏳ NVIDIA API — Reserved for Future Use</h3>\n            <p style=\"color: #94a3b8;\">The NVIDIA endpoint is configured and ready. Add <code>NVIDIA_API_KEY</code> in\n                Azure to activate it.</p>\n            <div class=\"endpoint-box\" style=\"color: rgba(148, 163, 184, 0.5);\">\n                POST https://prism-ai-browser-api-hcb9hra7e8eecjca.centralindia-01.azurewebsites.net/api/nvidia-chat\n            </div>\n        </div>\n\n        <div class=\"info-note\">\n            💡 <strong>How it works:</strong> Your frontend sends requests to the Azure Function URL (no API key needed\n            in the request). The Azure Function injects the secret API key server-side and proxies the request to\n            Groq/NVIDIA. This means your code is safe to push to GitHub.\n        </div>\n    </main>",
  "scripts": [],
  "externalScripts": []
};

export const title = page.title;

export default function ConfigLoader() {
  return <LegacyHtmlPage {...page} />;
}
