import LegacyHtmlPage from '@/components/legacy/LegacyHtmlPage';

const page = {
  "documentClassName": "legacy-tool-document",
  "bodyClassName": "legacy-tool-route",
  "title": "PRISM Config Status",
  "headMarkup": "<style>\n        body {\n            margin: 0;\n            min-height: 100vh;\n            font-family: \"Segoe UI\", Arial, sans-serif;\n            background: linear-gradient(180deg, #07111f 0%, #0f172a 100%);\n            color: #e2e8f0;\n            display: grid;\n            place-items: center;\n        }\n\n        .panel {\n            width: min(680px, calc(100vw - 32px));\n            background: rgba(15, 23, 42, 0.92);\n            border: 1px solid rgba(148, 163, 184, 0.22);\n            border-radius: 18px;\n            padding: 24px;\n            box-shadow: 0 24px 80px rgba(0, 0, 0, 0.35);\n        }\n\n        h1 {\n            margin: 0 0 8px;\n            font-size: 28px;\n        }\n\n        p {\n            margin: 0 0 16px;\n            color: #cbd5e1;\n            line-height: 1.5;\n        }\n\n        .status-card {\n            background: rgba(52, 211, 153, 0.08);\n            border: 1px solid rgba(52, 211, 153, 0.25);\n            border-radius: 12px;\n            padding: 16px;\n            margin-bottom: 16px;\n        }\n\n        .status-card h3 {\n            margin: 0 0 8px;\n            font-size: 16px;\n            color: #34d399;\n        }\n\n        .status-card p {\n            margin: 0;\n            font-size: 14px;\n            color: #a7f3d0;\n        }\n\n        .endpoint-box {\n            background: #020617;\n            border: 1px solid rgba(148, 163, 184, 0.24);\n            border-radius: 10px;\n            padding: 14px;\n            font: 13px/1.5 Consolas, \"Courier New\", monospace;\n            color: #93c5fd;\n            word-break: break-all;\n            margin-top: 8px;\n        }\n\n        code {\n            background: rgba(148, 163, 184, 0.12);\n            padding: 2px 6px;\n            border-radius: 6px;\n        }\n\n        .info-note {\n            background: rgba(96, 165, 250, 0.08);\n            border: 1px solid rgba(96, 165, 250, 0.2);\n            border-radius: 10px;\n            padding: 14px;\n            font-size: 13px;\n            color: #93c5fd;\n            line-height: 1.6;\n        }\n    </style>",
  "bodyMarkup": "<main class=\"panel\">\n        <h1>🚀 PRISM AI Backend</h1>\n        <p>Your AI tools now route through the <strong>Prism Space Cloud Run backend</strong>. No API keys are stored in the extension or exposed client-side.</p>\n\n        <div class=\"status-card\">\n            <h3>✅ Google Gemini — Active Provider</h3>\n            <p>The page assistant and all Dev Space tools use the Cloud Run backend. The AI provider is configured server-side via the <code>AI_PROVIDER</code> environment variable.</p>\n            <div class=\"endpoint-box\">\n                POST https://prismspace-backend-vk4s7gl22q-el.a.run.app/chat\n            </div>\n        </div>\n\n        <div class=\"status-card\" style=\"border-color: rgba(148, 163, 184, 0.2); background: rgba(148, 163, 184, 0.05);\">\n            <h3 style=\"color: #94a3b8;\">⚙️ Groq — Available as Fallback</h3>\n            <p style=\"color: #94a3b8;\">Set <code>AI_PROVIDER=groq</code> on the Cloud Run service to switch to Groq. No extension update required.</p>\n            <div class=\"endpoint-box\" style=\"color: rgba(148, 163, 184, 0.5);\">\n                POST https://prismspace-backend-vk4s7gl22q-el.a.run.app/chat (AI_PROVIDER=groq)\n            </div>\n        </div>\n\n        <div class=\"info-note\">\n            💡 <strong>How it works:</strong> The extension sends only page context (title, URL, content) to the Cloud Run backend. All prompt construction, AI provider selection, and API key management happen on the server. This means your extension code is safe to push to GitHub.\n        </div>\n    </main>",
  "scripts": [],
  "externalScripts": []

};

export const title = page.title;

export default function ConfigLoader() {
  return <LegacyHtmlPage {...page} />;
}
